"""Protocols for swapping the review data store in tests."""

from __future__ import annotations

from typing import Protocol

from app.models import EvaluationTask, Invite


class ReviewStore(Protocol):
    def get_invite_by_token(self, token: str) -> Invite | None: ...

    def get_or_create_session(self, invite_id: str) -> str: ...

    def get_next_evaluation_task(self, session_id: str) -> EvaluationTask | None: ...

    def get_evaluation_task(self, task_id: str) -> EvaluationTask | None: ...

    def list_all_evaluation_tasks(self) -> list[EvaluationTask]: ...

    def list_completed_tasks(self, session_id: str) -> list[EvaluationTask]: ...

    def get_task_round_number(self, task_id: str) -> int: ...

    def get_accepted_image_ids(self, session_id: str, task_id: str) -> set[str]: ...

    def count_evaluation_tasks(self) -> int: ...

    def count_completed_tasks(self, session_id: str) -> int: ...

    def has_feedback_for_session_task(self, session_id: str, task_id: str) -> bool: ...

    def submit_feedback(
        self,
        session_id: str,
        task_id: str,
        selections: dict[str, bool],
    ) -> None: ...
